### ISSUE TITLE
运行后在绑定时提示resolve3未被定义 绑定出错

### ISSUE THREAD

**Issue by CatSodaaa** [SonderXiaoming/pcrjjc_huannai#1]
查询main.py文件后定义是存在的 大佬看看这个问题怎么解决
![1665973863166](https://user-images.githubusercontent.com/115628315/196076959-9c554d9f-286d-46b7-95eb-dbaead55775a.jpg)
![1665974136426](https://user-images.githubusercontent.com/115628315/196077297-b1ddb053-f00e-4601-80e2-30c661a696a0.jpg)
![1665974237479](https://user-images.githubusercontent.com/115628315/196077306-1017676a-3be1-4d01-b35d-ab789216a486.jpg)

**Comment by SonderXiaoming** [comment]
要不你把这个resolve3这个函数放开头？

**Comment by CatSodaaa** [comment]
> 要不你把这个resolve3这个函数放开头？

save_binds,resolve 0 1 2 3这几个函数放开头之后确实能跑起来 也能查询到竞技场数据 就是会有warning提示 如下 会有影响吗
![1665977588793](https://user-images.githubusercontent.com/115628315/196083750-575be5b9-169a-4ced-b3c0-2a9a353e9dea.jpg)

**Comment by duoshoumiao** [comment]
你们问题解决了吗
