### ISSUE TITLE
请问大佬有时间缝一个台服的嘛

### ISSUE THREAD

**Issue by Mira19971102** [SonderXiaoming/pcrjjc_huannai#11]
台服的可以帮忙缝一下嘛。。我觉得大佬你们这个环奈版做的挺好的

**Comment by SonderXiaoming** [comment]
台服我记得是四个服务器来着，逻辑有点区别，再者说我不玩台服，没有号，也不知道怎么下载

**Comment by Mira19971102** [comment]
我可以把我现在用的项目发你，方便扣扣啥的私信嘛，配置我都有，一些简单的设置也懂点，但台服的功能远不如你的国服环奈版强大完整，我的扣扣1486404395
