### ISSUE TITLE
过验证码服务炸了么

### ISSUE THREAD

**Issue by CatSodaaa** [SonderXiaoming/pcrjjc_huannai#12]
![image](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/115628315/5fc192c9-498d-4994-b271-cfa2e03e3e4d)
如图所示 提示是过码出问题了 账号本身是登的上去的

**Comment by SonderXiaoming** [comment]
可以试试改密码/找路路

**Comment by CatSodaaa** [comment]
> 可以试试改密码/找路路

密码修改了还是这样。。。 那么有路路佬的联系方式吗 或者是星乃群号给个 麻烦一下了

**Comment by SonderXiaoming** [comment]
星乃群711462207

**Comment by CatSodaaa** [comment]
> 星乃群711462207

提一嘴 旧版本pcrjjc2-main 手动过下验证还是能用的 路佬没动静先用这个过渡下啦

**Comment by along411** [comment]
> > 星乃群711462207
> 
> 提一嘴 旧版本PCRJJC2-main 手动过下验证还是能用的 路佬没动静先用这个过渡下啦

旧版PCRJJC2-main这个版本需要改什么吗，我改了一下版本号用就一直提示返回标题

**Comment by CatSodaaa** [comment]
> > > 星乃群711462207
> > 
> > 
> > 提一嘴 旧版本PCRJJC2-main 手动过下验证还是能用的 路佬没动静先用这个过渡下啦
> 
> 旧版PCRJJC2-main这个版本需要改什么吗，我改了一下版本号用就一直提示返回标题

pcrclient.py里面的apiroot这行 将http改成https即可

**Comment by along411** [comment]
> > > > 星乃群711462207
> > > 
> > > 
> > > 提一嘴 旧版本PCRJJC2-main 手动过下验证还是能用的 路佬没动静先用这个过渡下啦
> > 
> > 
> > 旧版PCRJJC2-main这个版本需要改什么吗，我改了一下版本号用就一直提示返回标题
> 
> pcrclient.py里面的apiroot这行 将http改成https即可

好的谢谢
