### ISSUE TITLE
请问这个插件怎么启用手动过码呀

### ISSUE THREAD

**Issue by ghost** [SonderXiaoming/pcrjjc_huannai#14]

**Comment by ghost** [comment]
感谢

**Comment by ybl233** [comment]
![Uploading J)6(`KDOMTZ88B9(3~UIFDU.png…]()
出现了此错误

**Comment by ghost** [comment]
![1](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/65817642/a3de40ff-8124-40a8-b7b3-8f34dcb00acc)
请问出现此情况应该怎么弄啊

**Comment by kcn3388** [comment]
> ![1](https://user-images.githubusercontent.com/65817642/241241684-a3de40ff-8124-40a8-b7b3-8f34dcb00acc.jpg) 请问出现此情况应该怎么弄啊

更新新版本 @ybl233 

检查你的账号文件格式，应该是像这样的
```json
[
    {
        "account": "account1",
        "password": "password",
        "platform": 2,
        "channel": 1,
        "admin": 114514
    },
    {
        "account": "account2",
        "password": "password",
        "platform": 2,
        "channel": 1,
        "admin": 114514
    }
]
```

**Comment by ghost** [comment]
更新插件后，已可使用，感谢大佬
