### ISSUE TITLE
有关手动拼接验证码链接头与链接后无法进入页面的问题

### ISSUE THREAD

**Issue by Linby0912** [SonderXiaoming/pcrjjc_huannai#19]
![P7`YD)BM(`$2PA@V{JL6YZO](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/55955748/38c0277d-9ef4-4c92-b2d2-09dabbd093f5)
拼接ip:Host的链接头后会提示拒绝访问，拼接腾讯链接头会提示
![T 1~JL{{ES3QAI5Y9{Q`9HH](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/55955748/1ad829ad-0030-40a5-a5d0-2f505f8f09b9)
请问这种办法要如何解决@kcn3388

**Comment by Linby0912** [comment]
_**经询问大佬后得知要在腾讯链接头的geetest后面加一个_**_

但现在又产生了新的问题：手动过验证码后，一旦输入竞技场查询便会提示账号已风控，目前仍未得知解决方案

**Comment by kcn3388** [comment]
> _**经询问大佬后得知要在腾讯链接头的geetest后面加一个_**_
> 
> 但现在又产生了新的问题：手动过验证码后，一旦输入竞技场查询便会提示账号已风控，目前仍未得知解决方案


完整的链接应该形如下面的：

```
127.0.0.1:8080/geetest/?captcha_type=1&challenge={challenge}&gt={gt}&userid={userid}&gs=1
```
检查你是不是少了个问号

无法复现账号已风控提示，请检查你的操作

**Comment by kcn3388** [comment]
fix in #21 
修了自己服务器上的404，还有验证码网页被重复注册的问题

**Comment by dzh666666** [comment]
> > _**经询问大佬后得知要在腾讯链接头的吉斯特后面加一个_**_
> > 但现在又产生了新的问题：手动过验证码后,一旦输入竞技场查询便会提示账号已风控,目前仍未得知解决方案
> 
> 完整的链接应该形如下面的：
> 
> ```
> 127.0.0.1:8080/geetest/?captcha_type=1&challenge={challenge}&gt={gt}&userid={userid}&gs=1
> ```
> 
> 检查你是不是少了个问号
> 
> 无法复现账号已风控提示,请检查你的操作

我按照这种格式拼接后的网页还是打不开..

**Comment by kcn3388** [comment]
> 我按照这种格式拼接后的网页还是打不开..

更新新版本，新版本的服务器链接应该是形如这样的

```
你的IP:8080/geetest?captcha_type=1&challenge={challenge}&gt={gt}&userid={userid}&gs=1
```

**Comment by dzh666666** [comment]
你的IP:8080/geetest?captcha_type=1&challenge={challenge}&gt={gt}&userid={userid}&gs=1
新版本的也试了打不开

**Comment by kcn3388** [comment]
> 你的IP:8080/geetest?captcha_type=1&challenge={challenge}&gt={gt}&userid={userid}&gs=1 新版本的也试了打不开

看看你的链接长啥样

**Comment by dzh666666** [comment]
> > 你的IP:8080/geetest?captcha_type=1&challenge={challenge}&gt={gt}&userid={userid}&gs=1 新版本的也试了打不开
> 
> 看看你的链接长啥样
8.133.191.49:8080/geetest?captcha_type=1&challenge=2a2af8841b6817d91bfd4e31302cef82&gt=245273d7fa73f7b657098bf7441fe12f&userid=45212e45814d495a8471bae4e230e7da&gs=1

**Comment by kcn3388** [comment]
> > 看看你的链接长啥样
>
> 8.133.191.49:8080/geetest?captcha_type=1&challenge=2a2af8841b6817d91bfd4e31302cef82&gt=245273d7fa73f7b657098bf7441fe12f&userid=45212e45814d495a8471bae4e230e7da&gs=1

请确认你的IP是公网IP，并且开放了对应的端口，不是公网IP的话请在局域网内使用`127.0.0.1`作为IP或者使用备用链接头

**Comment by dzh666666** [comment]
> > > 看看你的链接长啥样
> > 
> > 
> > 8.133.191.49:8080/geetest?captcha_type=1&challenge=2a2af8841b6817d91bfd4e31302cef82&gt=245273d7fa73f7b657098bf7441fe12f&userid=45212e45814d495a8471bae4e230e7da&gs=1
> 
> 请确认你的IP是公网IP，并且开放了对应的端口，不是公网IP的话请在局域网内使用`127.0.0.1`作为IP或者使用备用链接头

是公网IP开放端口了不知道怎么回事  请问备用链接头的格式也是上面这种吗

**Comment by kcn3388** [comment]
> _**经询问大佬后得知要在腾讯链接头的geetest后面加一个_**_
> 
> 但现在又产生了新的问题：手动过验证码后，一旦输入竞技场查询便会提示账号已风控，目前仍未得知解决方案

这个

另外你确认你的是公网IP？

![image](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/25716090/e5029fa0-2170-44db-ae00-a3f9a3b234a0)

完全无法访问

**Comment by dzh666666** [comment]
> 

![QQ图片20230530161926](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/77667512/36fb99f2-ab55-4c95-88a0-462ccb3c4db5)
配置里写的是这个 进服务器里看的是第二个 不过都无法访问

**Comment by dzh666666** [comment]
> > _**经询问大佬后得知要在腾讯链接头的geetest后面加一个_**_
> > 但现在又产生了新的问题：手动过验证码后，一旦输入竞技场查询便会提示账号已风控，目前仍未得知解决方案
> 
> 这个
> 
> 另外你确认你的是公网IP？
> 
> ![image](https://user-images.githubusercontent.com/25716090/241892674-e5029fa0-2170-44db-ae00-a3f9a3b234a0.png)
> 
> 完全无法访问

使用备用链接头是404

**Comment by kcn3388** [comment]
> 使用备用链接头是404

更新插件，用插件反馈的链接头

如果是服务器，检查服务器系统自带的防火墙和阿里云的防火墙是否开放端口

你这两个IP都ping不通肯定有问题，找阿里云客服去

**Comment by dzh666666** [comment]
> > 使用备用链接头是404
> 
> 更新插件，用插件反馈的链接头
> 
> 如果是服务器，检查服务器系统自带的防火墙和阿里云的防火墙是否开放端口
> 
> 你这两个IP都ping不通肯定有问题，找阿里云客服去
好的谢谢大佬
