### ISSUE TITLE
我也遇到一样的问题，但是我没有能解决resolve3的问题

### ISSUE THREAD

**Issue by duoshoumiao** [SonderXiaoming/pcrjjc_huannai#2]
大佬如果解决了顺便更新一下吧。

**Comment by SonderXiaoming** [comment]
把resolve3函数放最前面？

**Comment by CatSodaaa** [comment]
> 把resolve3函数放最前面？

放前面 只有查询功能有效  上线提醒以及排名上升功能使用不了 被打提醒也没有  应该都是用hoshino的没道理啊 大佬你的没提前面也能正常使用吗？

**Comment by duoshoumiao** [comment]
用新版hoshino就解决了

**Comment by duoshoumiao** [comment]
> > 把resolve3函数放最前面？
> 
> 放前面 只有查询功能有效 上线提醒以及排名上升功能使用不了 被打提醒也没有 应该都是用hoshino的没道理啊 大佬你的没提前面也能正常使用吗？

用新版hoshino

**Comment by CatSodaaa** [comment]
> > > 把resolve3函数放最前面？
> > 
> > 
> > 放前面 只有查询功能有效 上线提醒以及排名上升功能使用不了 被打提醒也没有 应该都是用hoshino的没道理啊 大佬你的没提前面也能正常使用吗？
> 
> 用新版hoshino

确实 换新版的hoshino就没问题了
