### ISSUE TITLE
jjc绑定报错

### ISSUE THREAD

**Issue by pach128** [SonderXiaoming/pcrjjc_huannai#23]
您好，我把插件更新到最新版本以后jjc绑定就报错，下面是报错信息，可以帮忙看下这个是什么原因导致的吗？
![image](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/65009140/83841245-4379-44a3-82d7-f06d38d5d0c3)

**Comment by SonderXiaoming** [comment]
检查账号配置之类的，你这是没b站号在查导致的

**Comment by pach128** [comment]
![image](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/65009140/ec2b0acd-f16d-437a-bb14-1a765bb89f21)
额，是这里吗？这里我按格式填写了，以防万一找了2个号填写

**Comment by SonderXiaoming** [comment]
现在是不是维护了

**Comment by pach128** [comment]
￣□￣｜｜，原来是这个问题么。。。。尴尬，我等开服了再试试，谢谢dalao

**Comment by pach128** [comment]
已解决，非常感谢
