### ISSUE TITLE
手动过码无限失败

### ISSUE THREAD

**Issue by fgo000000** [SonderXiaoming/pcrjjc_huannai#24]
验证一次失败一次

**Comment by fgo000000** [comment]
但是公版jjc2插件可正常验证

**Comment by SonderXiaoming** [comment]
截图看报错

**Comment by Linby0912** [comment]
这个问题是你用第二个pcr号的登录验证ticket去验证了第一个pcr号产生的。每次手动过码会给你发送两次验证请求，每次请求包含三条消息，分别是threadx: Changed to manual；threadx: 自动过码多次尝试失败，可能为服务器错误，自动切换为手动。
确实服务器无误后，可发送 validatex auto重新触发自动过码；以及实际的验证请求。每次验证时，先验证第一次发来的请求，再验证第二次发来的请求即可解决

**Comment by pach128** [comment]
> 这个问题是你用第二个pcr号的登录验证ticket去验证了第一个pcr号产生的。每次手动过码会给你发送两次验证请求，每次请求包含三条消息，分别是threadx: Changed to manual；threadx: 自动过码多次尝试失败，可能为服务器错误，自动切换为手动。 确实服务器无误后，可发送 validatex auto重新触发自动过码；以及实际的验证请求。每次验证时，先验证第一次发来的请求，再验证第二次发来的请求即可解决

感谢dalao，我也遇到这个问题了，确实是这个原因，现在搞好了
