### ISSUE TITLE
只能手动查询没有触发自动报道功能

### ISSUE THREAD

**Issue by along411** [SonderXiaoming/pcrjjc_huannai#26]
![IJ~T 1XU%QVJEN1B PBE(`6](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/73514958/3d8f1ec5-3d29-4339-9a2c-96779833be43)
测试了双场排名上升与上线提醒

**Comment by SonderXiaoming** [comment]
你这是几个号在查？又绑定了多少号？我看好像是超时了，或者哪里卡住了

**Comment by along411** [comment]
> 你这是几个号在查？又绑定了多少号？我看好像是超时了，或者哪里卡住了

单个查询也是这种情况，一样的超时回复

**Comment by SonderXiaoming** [comment]
那说明你号过码失败或者需要换号

**Comment by along411** [comment]
> 



> 那说明你号过码失败或者需要换号

试了一下清空已绑定的ID也不行，只能手动查出结果

**Comment by along411** [comment]
更换帐号还是显示超时，且两个帐号游戏同时在线插件正常查询游戏也没掉不清楚是什么情况

**Comment by kcn3388** [comment]
`maximum number of running instances reached`这个报错一般是出现在pcr账号过码失败，检查你的用于查询排名的pcr账号是否成功登录。由于tx最近的风控问题，QQ有可能发私聊失败所以你没发现没过验证码。
[#2143](https://github.com/Mrs4s/go-cqhttp/issues/2143#issuecomment-1555884347)

**Comment by reine-ishyanami** [comment]
可能是定时任务模块没有成功加载

**Comment by duoshoumiao** [comment]
我今天更新后也出现这个bug了

**Comment by duoshoumiao** [comment]
多次重启和等待后终于平稳了
