### ISSUE TITLE
如果要绑定超过8个要怎么设置

### ISSUE THREAD

**Issue by duoshoumiao** [SonderXiaoming/pcrjjc_huannai#28]
如题

**Comment by reine-ishyanami** [comment]
1. `main.py`里面有一个搜索一个8的数值，改大
2. 如果数量要超过两位数的话需要修改那些有关于绑定序号的`@on_reg()`，把里面的`(\d)`改为`(\d+)`，应该就差不多了

**Comment by SonderXiaoming** [comment]
建议再来一个qq（最简单）

**Comment by duoshoumiao** [comment]
> 1. `main.py`里面有一个搜索一个8的数值，改大
> 2. 如果数量要超过两位数的话需要修改那些有关于绑定序号的`@on_reg()`，把里面的`(\d)`改为`(\d+)`，应该就差不多了

👌

**Comment by duoshoumiao** [comment]
> 建议再来一个qq（最简单）

我是绑定之后，改掉QQ号（随便瞎编一个）感觉重启麻烦
