### ISSUE TITLE
私聊验证码被拦截，有没有办法发指定群里

### ISSUE THREAD

**Issue by duoshoumiao** [SonderXiaoming/pcrjjc_huannai#29]
如题，重启好多次  都收不到验证码

**Comment by reine-ishyanami** [comment]
去用另一个版本的，那个版本修复了自动过码[pcrjjc_huannai2](https://github.com/SonderXiaoming/pcrjjc_huannai2)

**Comment by SonderXiaoming** [comment]
直接print效果一样
