### ISSUE TITLE
[BUG]绑定多个UID，只有序号为1的UID可以推送

### ISSUE THREAD

**Issue by PoiSuKi** [SonderXiaoming/pcrjjc_huannai#3]
可能是查询账号中一个寄了，导致功能出错（
--------------------
控制台中无报错，查询功能都是正常的，但推送功能只有序号为1的UID可以推送：
以下是绑定列表：
![1](https://user-images.githubusercontent.com/74838511/197319847-bf4b89ae-f07b-42b4-a55d-8969c54ba449.png)
但实际测试只有序号1的可以正常推送
求大佬指点_(:з)∠)_

**Comment by SonderXiaoming** [comment]
没遇到这个问题，你换新版hoshino？

**Comment by PoiSuKi** [comment]
> 没遇到这个问题，你换新版hoshino？

我是9月8号装的hoshino，应该已经是最新的了（

**Comment by SonderXiaoming** [comment]
标记一下，这是只绑一个账号好了，原先是两个，初步推测是一个寄了，我本人是三号
