### ISSUE TITLE
更新后竞技场功能失效

### ISSUE THREAD

**Issue by frlda** [SonderXiaoming/pcrjjc_huannai#31]
2023.12.15公主连结更新后报错 ，AES解密报错Invalid AES key length，https://github.com/666dechaoge/pcrjjc2_xcw/issues/9

**Comment by frlda** [comment]
![image](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/97551927/7e2fb845-88dd-45fe-97ac-ad9d8b6ff59d)
对应注释掉空响应api解决pcrclient.py第253行
![image](https://github.com/SonderXiaoming/pcrjjc_huannai/assets/97551927/75bd8c53-0c28-44a5-9d73-9a5f2515ba68)

**Comment by SonderXiaoming** [comment]
修了
