### ISSUE TITLE
竞技场无法查询

### ISSUE THREAD

**Issue by 1529960009** [SonderXiaoming/pcrjjc_huannai#7]
![QQ截图20221201184548](https://user-images.githubusercontent.com/45947734/205034033-dd1b57c6-d576-40a5-bb03-158bff0bcab6.png)

**Comment by HMScygnet** [comment]
号有问题，我换了个号能登了

**Comment by SonderXiaoming** [comment]
这是b站抽风，现在应该都好了（如果不好就再等一会）
