### ISSUE TITLE
4.9.7版本后，查询功能报错

### ISSUE THREAD

**Issue by 1529960009** [SonderXiaoming/pcrjjc_huannai#8]
![QQ截图20221221210403](https://user-images.githubusercontent.com/45947734/208912068-5afe8e29-6d21-470c-965d-a0a6a2b285bf.jpg)

**Comment by SonderXiaoming** [comment]
修改一下version.txt,把版本号改成4.9.7。好像是自动更新版本号寄了

**Comment by 1529960009** [comment]
版本号更新了，还是这个报错

**Comment by SonderXiaoming** [comment]
怪事，你print(res)看看，感觉你号问题

**Comment by 1529960009** [comment]
我尝试在安卓登录我的小号，登录之后，问题就没有了
